# Generated by Django 4.2.1 on 2023-05-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetology', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Информация администратора', 'verbose_name_plural': 'Информация администратора'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
