# Generated by Django 4.2.1 on 2023-05-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetology', '0003_service_is_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='location_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='location_longitude',
            field=models.FloatField(default=0),
        ),
    ]
