# Generated by Django 4.2.1 on 2023-06-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetology', '0004_owner_location_latitude_owner_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
