# Generated by Django 4.2.1 on 2023-07-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetology', '0005_client_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
